### ISSUE TITLE
Project path can not handle spaces and perhaps other characters

### ISSUE THREAD

**Issue by ArjenR** [jsseidel/draftmangtk#1]
Hi I wanted to try Draftman (coming from Scrivener).

The path where I keep my writing stuff has spaces and I could not create a project in the path.

Setting quotes around the path after selecting the project directory allowed me to create the project. So my guess is the path (and filename) variables are passed to some ot the functions in an unescaped form.

**Comment by jsseidel** [comment]
Not sure why I didn't see this before. In any case, I came here to report the same bug after trying to build a new project from a Scrivener export. I will fix this very soon.

**Comment by jsseidel** [comment]
Fix released.
